### ISSUE TITLE
Does it have a working example?

### ISSUE THREAD

**Issue by chenrui333** [scalding/gradle-waroverlay-plugin#4]
Did try both options:
1. integrate from maven project
2. build from branch https://github.com/Unicon/unicon-cas-overlay/tree/CAS4 (this even worse, it could not pass the build at all)

CAS version the same as 3.5.2

**Comment by scalding** [comment]
Could you describe what problems you're seeing? When I clone the `unicon-cas-overlay` and run `./gradlew clean war`, I was able to get a good `cas.war` file.

Also, this project is used in [https://github.com/UniconLabs/cas-strap].

**Comment by chenrui333** [comment]
@scalding I did not use cas-strap, I added gretty plugin, but it failed in the build.

**Comment by scalding** [comment]
Could you attach the output from your build?

**Comment by chenrui333** [comment]
https://github.com/chenrui333/cas-overlay-sample
This is also my sample project. 

It works with mvn clean jetty:run
but failed with ./gradlew clean jettyRun

Can you shed some idea on that as well? 

Thanks a lot,

**Comment by chenrui333** [comment]
@scalding this is what I just pushed 
https://github.com/chenrui333/unicon-cas-overlay/commits/CAS4-add-gretty-plugin

command I used: ./gradlew clean jettyRun

* Where:
Script 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin' line: 16

* What went wrong:
A problem occurred evaluating script.
> org/codehaus/groovy/runtime/typehandling/ShortTypeHandling

**Comment by chenrui333** [comment]
I will try with cas-strap now, but I'd rather prefer that we can do with jetty

**Comment by scalding** [comment]
Looks to be a problem with the gretty plugin. You should be seeing something like this:

```
> ./gradlew clean jettyRun
:clean
:prepareInplaceWebAppFolder
:createInplaceWebAppFolder UP-TO-DATE
:compileJava UP-TO-DATE
:processResources
:classes
:prepareInplaceWebAppClasses
:prepareInplaceWebApp
:jettyRun
09:59:11 INFO  No Spring WebApplicationInitializer types detected on classpath
09:59:11 INFO  Jetty 9.2.10.v20150310 started and listening on port 8080
09:59:11 INFO  cas-overlay-3.5.x runs at:
09:59:11 INFO    http://localhost:8080/cas-overlay-3.5.x
Press any key to stop the server.
09:59:28 INFO  No Spring WebApplicationInitializer types detected on classpath
> Building 88% > :jettyRun
```

Though, one other thing to note is that you won't be able to do an inplace exploded war without a bit of work since, by nature, a war overlay won't have all the required bits in place. You'd have to create a tmp directory to put everything in and use that as the war directory, or use the output from the `war` task as an archive

**Comment by chenrui333** [comment]
I changed to use jetty plugin, it still did not work. 
https://github.com/chenrui333/unicon-cas-overlay/tree/CAS4-add-gretty-plugin

Will try cas-strap now.

**Comment by chenrui333** [comment]
What is the secret sauce for cas-strap, it works pretty good. When I tried to compare with the normal gradlew, it is pretty much the same.

```
>diff cas-strap ../cas-overlay-3.5.x/gradlew
45,49d44
< # For Cygwin, ensure paths are in UNIX format before anything is touched.
< if $cygwin ; then
<     [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
< fi
< 
64c59
< cd "`dirname \"$PRG\"`/" >&-
---
> cd "`dirname \"$PRG\"`/" >/dev/null
66c61
< cd "$SAVED" >&-
---
> cd "$SAVED" >/dev/null
116a112
>     JAVACMD=`cygpath --unix "$JAVACMD"`

diff ../cl-cas/gradlew ../cas-overlay-3.5.x/gradlew
>> identical
```

**Comment by chenrui333** [comment]
I guess the reason is because embedded tomcat plugins?

**Comment by scalding** [comment]
cas-strap is just a rebranded gradle. Early on, there was a question of why use gradle when the CAS project used maven, so to hide that, I just renamed the wrapper script. It is, indeed, just gradle. Of course, now CAS is starting to use gradle, so there's probably no reason to hide that any more.

One day, I'll rework it to use something like the gretty plugin rather than specifically the tomcat plugin to allow the user to choose which container to run in.

**Comment by chenrui333** [comment]
@scalding Thanks for the quick reply, so you mean, if I change to use tomcat, it should work, right?
I will test that idea.

**Comment by chenrui333** [comment]
I will create another ticket for making jetty work with this plugin.

**Comment by chenrui333** [comment]
Thanks for the help!!
